#!/usr/bin/env bash
# Comment

#!/bin/bash
if [ -e school ]
then
    echo "school file exists"
    if [ -f school ]
    then
        if [ -s school ]
        then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
        echo "school is a regular file"
    else
        if [ -s school ]
        then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    fi
else
    echo "school file does not exist"
fi
